### PR TITLE
fix: prevent mobile to desktop version redirect

### PR DESCRIPTION
**Pull request by logeen**
Unfortunately #62 issue has occurred again :( Facebook automatically redirects (HTTP 301 response) every https://m.facebook.com/home.php HTTP request to desktop version https://www.facebook.com/. The only solution is to rewrite User-Agent HTTP header to convince Facebook that HTTP request was sent from mobile browser.

PS: Rewriting User-Agent header simply in `window.fetch` function doesn't work in Chrome.

### CODE REVIEW

**Comment by logeen** [comment]
@ArnaudLigny, please take a look

**Comment by ArnaudLigny** [comment]
Merged and deployed, now I'm waiting for the webstore validation (because of new required permissions).

**Comment by piobaire24** [comment]
Hi @ArnaudLigny 
Thanks for promptly getting onto this issue. Unfortunately the problem remains.
The F-Notifier icon just shows a question mark 
image

However, clicking the icon does open the relevant Facebook page.

Thanks!
Geoff

**Comment by dan073eb** [comment]
Mine was updated a month ago and seemed to fix the issue of just seeing the question mark, but now for some reason the question mark is back.  Any progress?

Thanks, 
Dan

**Comment by ArnaudLigny** [comment]
Hello @dan073eb, I thinks it's related to the new policy about cookies...
Could you create a dedicated issue? Thx.

**Pull request merged**
